server:
  port: 9099

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_example?serverTimezone=GMT%2B1
    username: root
    password: root
  mvc:
    # 出现错误时，直接抛出异常
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # 不要为我们工程中的资源文件建立映射
      add-mappings: false


